# Generated by Django 2.1 on 2020-06-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaMentions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('publication_date', models.DateField()),
                ('attribution_type', models.CharField(help_text='E.g. Quote, Feature, Mention, Research, By-line, Op-Ed', max_length=15)),
                ('last_name', models.CharField(max_length=30)),
                ('andrew_id', models.CharField(max_length=35)),
                ('category', models.CharField(max_length=75)),
                ('publication', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('article_link', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
    ]
