# Generated by Django 2.1 on 2020-06-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_table_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaMentions',
            new_name='MediaMention',
        ),
    ]
